name: Deploy B2C Policies

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy Policies to Azure B2C
      uses: azure-ad-b2c/deploy-trustframework-policy@v5
      with:
        folder: ./src
        files: '*_TEST.xml'
        tenant: ${{ secrets.B2C_TENANT_NAME }}
        clientId: ${{ secrets.AZURE_CLIENT_ID }}
        clientSecret: ${{ secrets.CLIENTSECRET }}
        renumberSteps: true
