name: Deploy B2C Policies

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy Policies to Azure B2C
      uses: b2c/src/custom-policies@v5
      with:
        folder: ./src/custom-policies
        files: |
          TrustFrameworkBase.xml
          TrustFrameworkExtensions.xml
          TrustFrameworkLocalization.xml
          SignUpOrSignin.xml
        tenant: ${{ secrets.B2C_TENANT_NAME }}
        clientId: ${{ secrets.AZURE_CLIENT_ID }}
        clientSecret: ${{ secrets.CLIENTSECRET }}
      
