name: Deploy B2C Policies

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Deploy Policies
      run: node github-action-runtime/index.js
      env:
        B2C_TENANT_NAME: ${{ secrets.B2C_TENANT_NAME }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
