name: Deploy B2C Policies

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy Policies to Azure B2C
      run: |
        cd $GITHUB_WORKSPACE/b2c/deploy-trustframework-policies-main
      